#!/bin/bash

#Busca dispositivos usb
usb=$(lsblk -fm | sed '/sda/d' | grep ^sd.)

if [ -z $usb ]
then
	zenity --error --title="No encontrado" --text="No se ha encontrado ningún dispositivo usb conectado al equipo."
exit
fi
#busca la cantidad de dispositivos conectados: sdb, sdc, sdd
sdb=$(lsblk -fm | grep ^sdb)
sdc=$(lsblk -fm | grep ^sdc)
sdd=$(lsblk -fm | grep ^sdd)

#Guarda información de cada dispositivo que encuentre: sdb sdc sdd
if [ -z $sdb ]
then
$sdb=""
else
sdbinfo=$(lsblk -fm |grep ^sdb |tr -s " " |sed 's/sdb//g')
fi

if [ -z $sdc ]
then
$sdc=""
else
sdcinfo=$(lsblk -fm | grep ^sdc |tr -s " " | sed 's/sdc//g')
fi

if [ -z $sdd ]
then
$sdd=""
else 
sddinfo=$(lsblk -fm | grep ^sdd |tr -s " " | sed 's/sdd//g')
fi

iso=$(zenity --file-selection --title="Seleciona una .iso" --file-selection --file-filter='ISO files (iso) | *.iso')

if [ -z $iso ]
then
	exit
fi
info=$(zenity --list --text="¿A dónde desea copiar la iso?\nMarque una opción antes de continuar." --width=450 --height=300 --column "Dispositivo" --column "Información" "$sdb" "$sdbinfo" "$sdc" "$sdcinfo" "$sdd" "$sddinfo")


if [ -z $info ]
then
exit
fi

continue=$(zenity --question --title="¿Desea continuar?" --text="ATENCIÓN: Se copiará $iso a /dev/$info y se desmontará el dispositivo automáticamente al finalizar.\nSE BORRARÁN TODAS LAS PARTICIONES Y TODOS LOS DATOS de $info.\nCuando pulse aceptar empezará la copia, se le notificará al finalizar.")


pkexec dd bs=4M if=$iso of=/dev/$info
umount /dev/$info
zenity --info --title="DDB" --text="Finalizado"
